// <auto-generated />
using System;
using FusionDb.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FusionDb.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FusionDbContext))]
    [Migration("20260613191823_InitialCollections")]
    partial class InitialCollections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FusionDb.Domain.Collections.AiCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_overlap");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_size");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("embedding_model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VectorDimensions")
                        .HasColumnType("integer")
                        .HasColumnName("vector_dimensions");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ai_collections", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_collections_chunk_overlap", "chunk_overlap >= 0 AND chunk_overlap < chunk_size");

                            t.HasCheckConstraint("ck_ai_collections_chunk_size", "chunk_size > 0");

                            t.HasCheckConstraint("ck_ai_collections_vector_dimensions", "vector_dimensions > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
