// <auto-generated />
using System;
using FusionDb.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FusionDb.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FusionDbContext))]
    [Migration("20260613200041_AddDocumentChunks")]
    partial class AddDocumentChunks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FusionDb.Domain.Collections.AiCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_overlap");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_size");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("embedding_model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VectorDimensions")
                        .HasColumnType("integer")
                        .HasColumnName("vector_dimensions");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ai_collections", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_collections_chunk_overlap", "chunk_overlap >= 0 AND chunk_overlap < chunk_size");

                            t.HasCheckConstraint("ck_ai_collections_chunk_size", "chunk_size > 0");

                            t.HasCheckConstraint("ck_ai_collections_vector_dimensions", "vector_dimensions > 0");
                        });
                });

            modelBuilder.Entity("FusionDb.Domain.Documents.AiDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("MetadataJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MetadataJson"), "gin");

                    b.HasIndex("Status");

                    b.HasIndex("CollectionId", "ContentHash");

                    b.ToTable("ai_documents", (string)null);
                });

            modelBuilder.Entity("FusionDb.Domain.Documents.AiDocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkNumber")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_number");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<int>("EndOffset")
                        .HasColumnType("integer")
                        .HasColumnName("end_offset");

                    b.Property<int>("StartOffset")
                        .HasColumnType("integer")
                        .HasColumnName("start_offset");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentId", "ChunkNumber")
                        .IsUnique();

                    b.ToTable("ai_document_chunks", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_document_chunks_number", "chunk_number > 0");

                            t.HasCheckConstraint("ck_ai_document_chunks_offsets", "start_offset >= 0 AND end_offset > start_offset");
                        });
                });

            modelBuilder.Entity("FusionDb.Domain.Documents.AiDocument", b =>
                {
                    b.HasOne("FusionDb.Domain.Collections.AiCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FusionDb.Domain.Documents.AiDocumentChunk", b =>
                {
                    b.HasOne("FusionDb.Domain.Documents.AiDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
